use tiendaDB;

db.clientes.insertMany([
  { nombre: "Abel Smith", email: "abel.smith@example.com", genero: "Masculino", pais: "CR", preferencias: {canal: ["WEB"]} },
  { nombre: "Abigail Johnson", email: "abigail.johnson@example.com", genero: "Femenino", pais: "AR", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Alan Williams", email: "alan.williams@example.com", genero: "Masculino", pais: "PE", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Analía Brown", email: "analia.brown@example.com", genero: "Femenino", pais: "UY", preferencias: {canal: ["WEB"]} },
  { nombre: "Ayelén Jones", email: "ayelen.jones@example.com", genero: "Femenino", pais: "BB", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Bianca Garcia", email: "bianca.garcia@example.com", genero: "Femenino", pais: "US", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Bibiana Miller", email: "bibiana.miller@example.com", genero: "Femenino", pais: "BZ", preferencias: {canal: ["WEB"]} },
  { nombre: "Brenda Davis", email: "brenda.davis@example.com", genero: "Femenino", pais: "JM", preferencias: {canal: ["WEB"]} },
  { nombre: "Camila Rodriguez", email: "camila.rodriguez@example.com", genero: "Femenino", pais: "CO", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Carina Martinez", email: "carina.martinez@example.com", genero: "Femenino", pais: "SV", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Celina Hernandez", email: "celina.hernandez@example.com", genero: "Femenino", pais: "HN", preferencias: {canal: ["WEB"]} },
  { nombre: "Christian Lopez", email: "christian.lopez@example.com", genero: "Masculino", pais: "PA", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Cinthia Gonzalez", email: "cinthia.gonzalez@example.com", genero: "Femenino", pais: "EC", preferencias: {canal: ["WEB"]} },
  { nombre: "Cintia Wilson", email: "cintia.wilson@example.com", genero: "Femenino", pais: "GD", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Claribel Anderson", email: "claribel.anderson@example.com", genero: "Femenino", pais: "VE", preferencias: {canal: ["WEB"]} },
  { nombre: "Clarissa Thomas", email: "clarissa.thomas@example.com", genero: "Femenino", pais: "LC", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Cynthia Taylor", email: "cynthia.taylor@example.com", genero: "Femenino", pais: "CA", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Daiana Moore", email: "daiana.moore@example.com", genero: "Femenino", pais: "AR", preferencias: {canal: ["WEB"]} },
  { nombre: "Dalila Jackson", email: "dalila.jackson@example.com", genero: "Femenino", pais: "BR", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Dalma Martin", email: "dalma.martin@example.com", genero: "Femenino", pais: "BO", preferencias: {canal: ["WEB"]} },
  { nombre: "Dámaris Lee", email: "damaris.lee@example.com", genero: "Femenino", pais: "HT", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Débora Perez", email: "debora.perez@example.com", genero: "Femenino", pais: "PY", preferencias: {canal: ["WEB"]} },
  { nombre: "Eleonora Thompson", email: "eleonora.thompson@example.com", genero: "Femenino", pais: "SR", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Eliana White", email: "eliana.white@example.com", genero: "Femenino", pais: "CR", preferencias: {canal: ["WEB"]} },
  { nombre: "Elsa Harris", email: "elsa.harris@example.com", genero: "Femenino", pais: "CL", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Érica Sanchez", email: "erica.sanchez@example.com", genero: "Femenino", pais: "NI", preferencias: {canal: ["WEB"]} },
  { nombre: "Erick Clark", email: "erick.clark@example.com", genero: "Masculino", pais: "PE", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Estefanía Ramirez", email: "estefania.ramirez@example.com", genero: "Femenino", pais: "JM", preferencias: {canal: ["WEB"]} },
  { nombre: "Fabiana Lewis", email: "fabiana.lewis@example.com", genero: "Femenino", pais: "AR", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Fanny Robinson", email: "fanny.robinson@example.com", genero: "Femenino", pais: "TT", preferencias: {canal: ["WEB"]} },
  { nombre: "Gabriela Walker", email: "gabriela.walker@example.com", genero: "Femenino", pais: "PA", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Gianina Young", email: "gianina.young@example.com", genero: "Femenino", pais: "HT", preferencias: {canal: ["WEB"]} },
  { nombre: "Giannina Allen", email: "giannina.allen@example.com", genero: "Femenino", pais: "BZ", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Gimena King", email: "gimena.king@example.com", genero: "Femenino", pais: "CL", preferencias: {canal: ["WEB"]} },
  { nombre: "Giorgina Wright", email: "giorgina.wright@example.com", genero: "Femenino", pais: "DM", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Gisela Scott", email: "gisela.scott@example.com", genero: "Femenino", pais: "UY", preferencias: {canal: ["WEB"]} },
  { nombre: "Gisele Torres", email: "gisele.torres@example.com", genero: "Femenino", pais: "MX", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Giselle Nguyen", email: "giselle.nguyen@example.com", genero: "Femenino", pais: "CO", preferencias: {canal: ["WEB"]} },
  { nombre: "Gissele Hill", email: "gissele.hill@example.com", genero: "Otro", pais: "AR", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Gisselle Flores", email: "gisselle.flores@example.com", genero: "Femenino", pais: "VC", preferencias: {canal: ["WEB"]} },
  { nombre: "Graciela Green", email: "graciela.green@example.com", genero: "Femenino", pais: "SR", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Griselda Adams", email: "griselda.adams@example.com", genero: "Femenino", pais: "HN", preferencias: {canal: ["WEB"]} },
  { nombre: "Iliana Nelson", email: "iliana.nelson@example.com", genero: "Femenino", pais: "CU", preferencias: {canal: ["WEB"]} },
  { nombre: "Ivana Baker", email: "ivana.baker@example.com", genero: "Femenino", pais: "JM", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Jésica Hall", email: "jesica.hall@example.com", genero: "Femenino", pais: "TT", preferencias: {canal: ["WEB"]} },
  { nombre: "Jimena Rivera", email: "jimena.rivera@example.com", genero: "Otro", pais: "CR", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Judith Campbell", email: "judith.campbell@example.com", genero: "Femenino", pais: "VC", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Julieta Mitchell", email: "julieta.mitchell@example.com", genero: "Femenino", pais: "EC", preferencias: {canal: ["WEB"]} },
  { nombre: "Karen Carter", email: "karen.carter@example.com", genero: "Femenino", pais: "BO", preferencias: {canal: ["WEB"]} },
  { nombre: "Karina Roberts", email: "karina.roberts@example.com", genero: "Femenino", pais: "VE", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Katia Gomez", email: "katia.gomez@example.com", genero: "Femenino", pais: "HN", preferencias: {canal: ["WEB"]} },
  { nombre: "Kevin Phillips", email: "kevin.phillips@example.com", genero: "Masculino", pais: "US", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Kiara Evans", email: "kiara.evans@example.com", genero: "Femenino", pais: "AR", preferencias: {canal: ["WEB"]} },
  { nombre: "Letizia Turner", email: "letizia.turner@example.com", genero: "Femenino", pais: "PE", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Liu Diaz", email: "liu.diaz@example.com", genero: "Femenino", pais: "SR", preferencias: {canal: ["WEB"]} },
  { nombre: "Luciana Parker", email: "luciana.parker@example.com", genero: "Femenino", pais: "JM", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Lucila Cruz", email: "lucila.cruz@example.com", genero: "Femenino", pais: "BZ", preferencias: {canal: ["WEB"]} },
  { nombre: "Lucrecia Edwards", email: "lucrecia.edwards@example.com", genero: "Femenino", pais: "MX", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Ludmila Collins", email: "ludmila.collins@example.com", genero: "Femenino", pais: "DM", preferencias: {canal: ["WEB"]} },
  { nombre: "Mabel Reyes", email: "mabel.reyes@example.com", genero: "Femenino", pais: "PY", preferencias: {canal: ["WEB"]} },
  { nombre: "Maia Stewart", email: "maia.stewart@example.com", genero: "Femenino", pais: "VC", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Maira Morris", email: "maira.morris@example.com", genero: "Femenino", pais: "AR", preferencias: {canal: ["WEB"]} },
  { nombre: "Malena Morales", email: "malena.morales@example.com", genero: "Femenino", pais: "GY", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Malvina Murphy", email: "malvina.murphy@example.com", genero: "Femenino", pais: "CO", preferencias: {canal: ["WEB"]} },
  { nombre: "Marianela Cook", email: "marianela.cook@example.com", genero: "Femenino", pais: "CR", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Marianella Rogers", email: "marianella.rogers@example.com", genero: "Femenino", pais: "HT", preferencias: {canal: ["WEB"]} },
  { nombre: "Maribel Gutierrez", email: "maribel.gutierrez@example.com", genero: "Femenino", pais: "BO", preferencias: {canal: ["WEB"]} },
  { nombre: "Mariela Ortiz", email: "mariela.ortiz@example.com", genero: "Femenino", pais: "AR", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Marisa Morgan", email: "marisa.morgan@example.com", genero: "Femenino", pais: "PA", preferencias: {canal: ["WEB"]} },
  { nombre: "Marisol Cooper", email: "marisol.cooper@example.com", genero: "Femenino", pais: "DM", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Mary Peterson", email: "mary.peterson@example.com", genero: "Femenino", pais: "MX", preferencias: {canal: ["WEB"]} },
  { nombre: "Mayra Bailey", email: "mayra.bailey@example.com", genero: "Otro", pais: "BO", preferencias: {canal: ["WEB"]} },
  { nombre: "Melody Reed", email: "melody.reed@example.com", genero: "Femenino", pais: "CL", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Mia Kelly", email: "mia.kelly@example.com", genero: "Femenino", pais: "GD", preferencias: {canal: ["WEB"]} },
  { nombre: "Michelle Howard", email: "michelle.howard@example.com", genero: "Femenino", pais: "JM", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Miriam Ramos", email: "miriam.ramos@example.com", genero: "Femenino", pais: "EC", preferencias: {canal: ["WEB"]} },
  { nombre: "Mirta Kim", email: "mirta.kim@example.com", genero: "Femenino", pais: "BZ", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Nadia Cox", email: "nadia.cox@example.com", genero: "Femenino", pais: "VE", preferencias: {canal: ["WEB"]} },
  { nombre: "Nancy Ward", email: "nancy.ward@example.com", genero: "Femenino", pais: "PE", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Nélida Richardson", email: "nelida.richardson@example.com", genero: "Femenino", pais: "AR", preferencias: {canal: ["WEB"]} },
  { nombre: "Nelly Watson", email: "nelly.watson@example.com", genero: "Femenino", pais: "TT", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Nelson Brooks", email: "nelson.brooks@example.com", genero: "Masculino", pais: "VC", preferencias: {canal: ["WEB"]} },
  { nombre: "Noemí Chavez", email: "noemi.chavez@example.com", genero: "Femenino", pais: "AG", preferencias: {canal: ["WEB"]} },
  { nombre: "Priscila Wood", email: "priscila.wood@example.com", genero: "Femenino", pais: "CL", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Priscilla James", email: "priscilla.james@example.com", genero: "Femenino", pais: "US", preferencias: {canal: ["WEB"]} },
  { nombre: "Rosana Bennett", email: "rosana.bennett@example.com", genero: "Femenino", pais: "JM", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Roxana Gray", email: "roxana.gray@example.com", genero: "Femenino", pais: "EC", preferencias: {canal: ["WEB"]} },
  { nombre: "Sabrina Mendoza", email: "sabrina.mendoza@example.com", genero: "Femenino", pais: "PY", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Silvana Ruiz", email: "silvana.ruiz@example.com", genero: "Femenino", pais: "CO", preferencias: {canal: ["WEB"]} },
  { nombre: "Solange Hughes", email: "solange.hughes@example.com", genero: "Femenino", pais: "CA", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Tamara Price", email: "tamara.price@example.com", genero: "Femenino", pais: "CR", preferencias: {canal: ["WEB"]} },
  { nombre: "Umberto Alvarez", email: "umberto.alvarez@example.com", genero: "Masculino", pais: "CL", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Vanessa Castillo", email: "vanessa.castillo@example.com", genero: "Femenino", pais: "GT", preferencias: {canal: ["WEB"]} },
  { nombre: "Vanina Sanders", email: "vanina.sanders@example.com", genero: "Femenino", pais: "GY", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Vannina Patel", email: "vannina.patel@example.com", genero: "Femenino", pais: "BO", preferencias: {canal: ["WEB"]} },
  { nombre: "Viviana Myers", email: "viviana.myers@example.com", genero: "Femenino", pais: "AR", preferencias: {canal: ["WEB","TIENDA"]} },
  { nombre: "Walter Long", email: "walter.long@example.com", genero: "Masculino", pais: "HN", preferencias: {canal: ["TIENDA"]} },
  { nombre: "Wendy Ross", email: "wendy.ross@example.com", genero: "Femenino", pais: "BZ", preferencias: {canal: ["WEB"]} },
  { nombre: "Ximena Foster", email: "ximena.foster@example.com", genero: "Femenino", pais: "PE", preferencias: {canal: ["WEB"]} },
  { nombre: "Yamila Jimenez", email: "yamila.jimenez@example.com", genero: "Femenino", pais: "PA", preferencias: {canal: ["TIENDA"]} }
]);

db.clientes.insertMany([
  { nombre: "Yanina Powell", email: "yanina.powell@example.com", genero: "Femenino", pais: "AR", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Yésica Jenkins", email: "yesica.jenkins@example.com", genero: "Femenino", pais: "CO", preferencias: { canal: ["WEB"] } },
  { nombre: "Zahira Perry", email: "zahira.perry@example.com", genero: "Femenino", pais: "CL", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Zaira Russell", email: "zaira.russell@example.com", genero: "Femenino", pais: "HN", preferencias: { canal: ["WEB"] } },
  { nombre: "Zulma Sullivan", email: "zulma.sullivan@example.com", genero: "Femenino", pais: "PE", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Aarón Bell", email: "aaron.bell@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB"] } },
  { nombre: "Abdón Coleman", email: "abdon.coleman@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Abel Butler", email: "abel.butler@example.com", genero: "Masculino", pais: "EC", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Abelardo Henderson", email: "abelardo.henderson@example.com", genero: "Masculino", pais: "JM", preferencias: { canal: ["WEB"] } },
  { nombre: "Abrahán Barnes", email: "abrahan.barnes@example.com", genero: "Masculino", pais: "BZ", preferencias: { canal: ["WEB"] } },
  { nombre: "Absalón Gonzales", email: "absalon.gonzales@example.com", genero: "Masculino", pais: "VE", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Acacio Fisher", email: "acacio.fisher@example.com", genero: "Masculino", pais: "PA", preferencias: { canal: ["WEB"] } },
  { nombre: "Adalberto Vasquez", email: "adalberto.vasquez@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Adán Simmons", email: "adan.simmons@example.com", genero: "Masculino", pais: "GY", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Adela Romero", email: "adela.romero@example.com", genero: "Femenino", pais: "US", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Adelaida Jordan", email: "adelaida.jordan@example.com", genero: "Femenino", pais: "BO", preferencias: { canal: ["WEB"] } },
  { nombre: "Adolfo Patterson", email: "adolfo.patterson@example.com", genero: "Masculino", pais: "TT", preferencias: { canal: ["WEB"] } },
  { nombre: "Adón Alexander", email: "adon.alexander@example.com", genero: "Masculino", pais: "DM", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Adrián Hamilton", email: "adrian.hamilton@example.com", genero: "Masculino", pais: "CL", preferencias: { canal: ["WEB"] } },
  { nombre: "Agustín Graham", email: "agustin.graham@example.com", genero: "Masculino", pais: "HT", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Aitor Reynolds", email: "aitor.reynolds@example.com", genero: "Masculino", pais: "GT", preferencias: { canal: ["WEB"] } },
  { nombre: "Alba Griffin", email: "alba.griffin@example.com", genero: "Femenino", pais: "CA", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Albert Wallace", email: "albert.wallace@example.com", genero: "Masculino", pais: "UY", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Alberto Moreno", email: "alberto.moreno@example.com", genero: "Masculino", pais: "BZ", preferencias: { canal: ["WEB"] } },
  { nombre: "Albina West", email: "albina.west@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["WEB"] } },
  { nombre: "Alejandra Cole", email: "alejandra.cole@example.com", genero: "Femenino", pais: "EC", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Alejandro Hayes", email: "alejandro.hayes@example.com", genero: "Masculino", pais: "SR", preferencias: { canal: ["WEB"] } },
  { nombre: "Alejo Bryant", email: "alejo.bryant@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Alfonso Herrera", email: "alfonso.herrera@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB"] } },
  { nombre: "Alfredo Gibson", email: "alfredo.gibson@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Alicia Ellis", email: "alicia.ellis@example.com", genero: "Femenino", pais: "JM", preferencias: { canal: ["WEB"] } },
  { nombre: "Alipio Tran", email: "alipio.tran@example.com", genero: "Masculino", pais: "HN", preferencias: { canal: ["WEB"] } },
  { nombre: "Almudena Medina", email: "almudena.medina@example.com", genero: "Femenino", pais: "CL", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Alonso Aguilar", email: "alonso.aguilar@example.com", genero: "Masculino", pais: "VE", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Álvaro Stevens", email: "alvaro.stevens@example.com", genero: "Masculino", pais: "PA", preferencias: { canal: ["WEB"] } },
  { nombre: "Amadeo Murray", email: "amadeo.murray@example.com", genero: "Masculino", pais: "GT", preferencias: { canal: ["WEB"] } },
  { nombre: "Amaro Ford", email: "amaro.ford@example.com", genero: "Masculino", pais: "EC", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Ambrosio Castro", email: "ambrosio.castro@example.com", genero: "Masculino", pais: "CL", preferencias: { canal: ["WEB"] } },
  { nombre: "Amelia Marshall", email: "amelia.marshall@example.com", genero: "Femenino", pais: "DM", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Amparo Owens", email: "amparo.owens@example.com", genero: "Femenino", pais: "US", preferencias: { canal: ["WEB"] } },
  { nombre: "Ana Harrison", email: "ana.harrison@example.com", genero: "Femenino", pais: "HN", preferencias: { canal: ["WEB"] } },
  { nombre: "Ananías Fernandez", email: "ananias.fernandez@example.com", genero: "Masculino", pais: "TT", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Anastasia Mcdonald", email: "anastasia.mcdonald@example.com", genero: "Femenino", pais: "BZ", preferencias: { canal: ["WEB"] } },
  { nombre: "Anatolio Woods", email: "anatolio.woods@example.com", genero: "Masculino", pais: "SR", preferencias: { canal: ["WEB"] } },
  { nombre: "Andrea Washington", email: "andrea.washington@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Andrés Kennedy", email: "andres.kennedy@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB"] } },
  { nombre: "Ángel Wells", email: "angel.wells@example.com", genero: "Masculino", pais: "GD", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Ángela Vargas", email: "angela.vargas@example.com", genero: "Femenino", pais: "JM", preferencias: { canal: ["WEB"] } },
  { nombre: "Ángeles Henry", email: "angeles.henry@example.com", genero: "Femenino", pais: "CL", preferencias: { canal: ["WEB"] } },
  { nombre: "Aniano Chen", email: "aniano.chen@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Anna Freeman", email: "anna.freeman@example.com", genero: "Femenino", pais: "GT", preferencias: { canal: ["WEB"] } },
  { nombre: "Anselmo Webb", email: "anselmo.webb@example.com", genero: "Masculino", pais: "NI", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Antero Tucker", email: "antero.tucker@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB"] } },
  { nombre: "Antonia Guzman", email: "antonia.guzman@example.com", genero: "Femenino", pais: "VE", preferencias: { canal: ["WEB"] } },
  { nombre: "Antonio Burns", email: "antonio.burns@example.com", genero: "Masculino", pais: "PA", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Aquiles Crawford", email: "aquiles.crawford@example.com", genero: "Masculino", pais: "UY", preferencias: { canal: ["WEB"] } },
  { nombre: "Araceli Olson", email: "araceli.olson@example.com", genero: "Femenino", pais: "JM", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Aránzazu Simpson", email: "aranzazu.simpson@example.com", genero: "Femenino", pais: "EC", preferencias: { canal: ["WEB"] } },
  { nombre: "Arcadio Porter", email: "arcadio.porter@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB"] } },
  { nombre: "Aresio Hunter", email: "aresio.hunter@example.com", genero: "Masculino", pais: "HT", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Ariadna Gordon", email: "ariadna.gordon@example.com", genero: "Femenino", pais: "DM", preferencias: { canal: ["WEB"] } },
  { nombre: "Aristides Mendez", email: "aristides.mendez@example.com", genero: "Masculino", pais: "GT", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Arnaldo Silva", email: "arnaldo.silva@example.com", genero: "Masculino", pais: "SV", preferencias: { canal: ["WEB"] } },
  { nombre: "Artemio Shaw", email: "artemio.shaw@example.com", genero: "Masculino", pais: "NI", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Arturo Snyder", email: "arturo.snyder@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB"] } },
  { nombre: "Ascensión Mason", email: "ascension.mason@example.com", genero: "Otro", pais: "GY", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Asunción Dixon", email: "asuncion.dixon@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["WEB"] } },
  { nombre: "Atanasio Munoz", email: "atanasio.munoz@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Augusto Hunt", email: "augusto.hunt@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB"] } },
  { nombre: "Áurea Hicks", email: "aurea.hicks@example.com", genero: "Femenino", pais: "CL", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Aurelia Holmes", email: "aurelia.holmes@example.com", genero: "Femenino", pais: "HN", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Aureliano Palmer", email: "aureliano.palmer@example.com", genero: "Masculino", pais: "BZ", preferencias: { canal: ["WEB"] } },
  { nombre: "Aurelio Wagner", email: "aurelio.wagner@example.com", genero: "Masculino", pais: "SR", preferencias: { canal: ["WEB"] } },
  { nombre: "Aurora Black", email: "aurora.black@example.com", genero: "Femenino", pais: "BO", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Baldomero Robertson", email: "baldomero.robertson@example.com", genero: "Masculino", pais: "GD", preferencias: { canal: ["WEB"] } },
  { nombre: "Balduino Boyd", email: "balduino.boyd@example.com", genero: "Masculino", pais: "PA", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Baltasar Rose", email: "baltasar.rose@example.com", genero: "Masculino", pais: "VE", preferencias: { canal: ["WEB"] } },
  { nombre: "Bárbara Stone", email: "barbara.stone@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Bartolomé Salazar", email: "bartolome.salazar@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB"] } },
  { nombre: "Basileo Fox", email: "basileo.fox@example.com", genero: "Masculino", pais: "PE", preferencias: { canal: ["WEB"] } },
  { nombre: "Beatriz Warren", email: "beatriz.warren@example.com", genero: "Femenino", pais: "JM", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Begoña Mills", email: "begona.mills@example.com", genero: "Otro", pais: "GT", preferencias: { canal: ["WEB"] } },
  { nombre: "Belén Meyer", email: "belen.meyer@example.com", genero: "Femenino", pais: "HN", preferencias: { canal: ["WEB"] } },
  { nombre: "Beltrán Rice", email: "beltran.rice@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Benedicto Schmidt", email: "benedicto.schmidt@example.com", genero: "Masculino", pais: "SR", preferencias: { canal: ["WEB"] } },
  { nombre: "Benigno Garza", email: "benigno.garza@example.com", genero: "Masculino", pais: "UY", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Benito Daniels", email: "benito.daniels@example.com", genero: "Masculino", pais: "GD", preferencias: { canal: ["WEB"] } },
  { nombre: "Benjamín Ferguson", email: "benjamin.ferguson@example.com", genero: "Masculino", pais: "PY", preferencias: { canal: ["WEB"] } },
  { nombre: "Bernabé Nichols", email: "bernabe.nichols@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Bernarda Stephens", email: "bernarda.stephens@example.com", genero: "Femenino", pais: "EC", preferencias: { canal: ["WEB"] } },
  { nombre: "Bernardo Soto", email: "bernardo.soto@example.com", genero: "Masculino", pais: "CL", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Blanca Weaver", email: "blanca.weaver@example.com", genero: "Femenino", pais: "VE", preferencias: { canal: ["WEB"] } },
  { nombre: "Blas Ryan", email: "blas.ryan@example.com", genero: "Masculino", pais: "BO", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Bonifacio Gardner", email: "bonifacio.gardner@example.com", genero: "Masculino", pais: "HT", preferencias: { canal: ["WEB"] } },
  { nombre: "Borja Payne", email: "borja.payne@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Bruno Grant", email: "bruno.grant@example.com", genero: "Masculino", pais: "JM", preferencias: { canal: ["WEB"] } },
  { nombre: "Calixto Dunn", email: "calixto.dunn@example.com", genero: "Masculino", pais: "CL", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Camilo Kelley", email: "camilo.kelley@example.com", genero: "Masculino", pais: "SR", preferencias: { canal: ["WEB"] } },
  { nombre: "Cándida Spencer", email: "candida.spencer@example.com", genero: "Femenino", pais: "GT", preferencias: { canal: ["WEB"] } },
  { nombre: "Carina Hawkins", email: "carina.hawkins@example.com", genero: "Femenino", pais: "CO", preferencias: { canal: ["WEB","TIENDA"] } }
]);

db.clientes.insertMany([
  { nombre: "Carlos Arnold", email: "carlos.arnold@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Carmelo Pierce", email: "carmelo.pierce@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB"] } },
  { nombre: "Carmen Vazquez", email: "carmen.vazquez@example.com", genero: "Femenino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Carolina Hansen", email: "carolina.hansen@example.com", genero: "Femenino", pais: "CL", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Casiano Peters", email: "casiano.peters@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB"] } },
  { nombre: "Casimiro Santos", email: "casimiro.santos@example.com", genero: "Masculino", pais: "US", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Casio Hart", email: "casio.hart@example.com", genero: "Masculino", pais: "EC", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Catalina Bradley", email: "catalina.bradley@example.com", genero: "Femenino", pais: "PE", preferencias: { canal: ["WEB"] } },
  { nombre: "Cayetano Knight", email: "cayetano.knight@example.com", genero: "Masculino", pais: "BZ", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Cayo Elliott", email: "cayo.elliott@example.com", genero: "Masculino", pais: "UY", preferencias: { canal: ["WEB"] } },
  { nombre: "Cecilia Cunningham", email: "cecilia.cunningham@example.com", genero: "Femenino", pais: "VE", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Ceferino Duncan", email: "ceferino.duncan@example.com", genero: "Masculino", pais: "PA", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Celia Armstrong", email: "celia.armstrong@example.com", genero: "Femenino", pais: "BO", preferencias: { canal: ["WEB"] } },
  { nombre: "Celina Hudson", email: "celina.hudson@example.com", genero: "Femenino", pais: "GD", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Celso Carroll", email: "celso.carroll@example.com", genero: "Masculino", pais: "HN", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "César Lane", email: "cesar.lane@example.com", genero: "Masculino", pais: "SV", preferencias: { canal: ["WEB"] } },
  { nombre: "Cesáreo Riley", email: "cesareo.riley@example.com", genero: "Masculino", pais: "JM", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Cipriano Andrews", email: "cipriano.andrews@example.com", genero: "Masculino", pais: "HT", preferencias: { canal: ["WEB"] } },
  { nombre: "Cirilo Alvarado", email: "cirilo.alvarado@example.com", genero: "Masculino", pais: "GT", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Cirino Ray", email: "cirino.ray@example.com", genero: "Masculino", pais: "SR", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Ciro Delgado", email: "ciro.delgado@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB"] } },
  { nombre: "Clara Berry", email: "clara.berry@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Claudia Perkins", email: "claudia.perkins@example.com", genero: "Femenino", pais: "BB", preferencias: { canal: ["WEB"] } },
  { nombre: "Claudio Hoffman", email: "claudio.hoffman@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Cleofás Johnston", email: "cleofas.johnston@example.com", genero: "Otro", pais: "DM", preferencias: { canal: ["WEB"] } },
  { nombre: "Clotilde Matthews", email: "clotilde.matthews@example.com", genero: "Femenino", pais: "BZ", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Colombo Pena", email: "colombo.pena@example.com", genero: "Masculino", pais: "EC", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Columba Richards", email: "columba.richards@example.com", genero: "Femenino", pais: "CU", preferencias: { canal: ["WEB"] } },
  { nombre: "Columbano Contreras", email: "columbano.contreras@example.com", genero: "Masculino", pais: "CL", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Concepción Willis", email: "concepcion.willis@example.com", genero: "Femenino", pais: "PE", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Conrado Carpenter", email: "conrado.carpenter@example.com", genero: "Masculino", pais: "US", preferencias: { canal: ["WEB"] } },
  { nombre: "Constancio Lawrence", email: "constancio.lawrence@example.com", genero: "Masculino", pais: "VE", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Constantino Sandoval", email: "constantino.sandoval@example.com", genero: "Masculino", pais: "UY", preferencias: { canal: ["WEB"] } },
  { nombre: "Consuelo Guerrero", email: "consuelo.guerrero@example.com", genero: "Femenino", pais: "MX", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Cosme George", email: "cosme.george@example.com", genero: "Masculino", pais: "GD", preferencias: { canal: ["WEB"] } },
  { nombre: "Cristian Chapman", email: "cristian.chapman@example.com", genero: "Masculino", pais: "PA", preferencias: { canal: ["WEB"] } },
  { nombre: "Cristina Rios", email: "cristina.rios@example.com", genero: "Femenino", pais: "HN", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Cristóbal Estrada", email: "cristobal.estrada@example.com", genero: "Masculino", pais: "JM", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Daciano Ortega", email: "daciano.ortega@example.com", genero: "Masculino", pais: "SV", preferencias: { canal: ["WEB"] } },
  { nombre: "Dacio Watkins", email: "dacio.watkins@example.com", genero: "Masculino", pais: "GT", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Dámaso Greene", email: "damaso.greene@example.com", genero: "Masculino", pais: "CA", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Damián Nunez", email: "damian.nunez@example.com", genero: "Masculino", pais: "BZ", preferencias: { canal: ["WEB"] } },
  { nombre: "Daniel Wheeler", email: "daniel.wheeler@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Dario Valdez", email: "dario.valdez@example.com", genero: "Masculino", pais: "BO", preferencias: { canal: ["WEB"] } },
  { nombre: "David Harper", email: "david.harper@example.com", genero: "Masculino", pais: "US", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Demócrito Burke", email: "democrito.burke@example.com", genero: "Masculino", pais: "PY", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Diego Larson", email: "diego.larson@example.com", genero: "Masculino", pais: "VE", preferencias: { canal: ["WEB"] } },
  { nombre: "Dimas Santiago", email: "dimas.santiago@example.com", genero: "Masculino", pais: "CA", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Dolores Maldonado", email: "dolores.maldonado@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["WEB"] } },
  { nombre: "Domingo Morrison", email: "domingo.morrison@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Donato Franklin", email: "donato.franklin@example.com", genero: "Masculino", pais: "DO", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Dorotea Carlson", email: "dorotea.carlson@example.com", genero: "Femenino", pais: "CL", preferencias: { canal: ["WEB"] } },
  { nombre: "Edgar Austin", email: "edgar.austin@example.com", genero: "Masculino", pais: "AG", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Edmundo Dominguez", email: "edmundo.dominguez@example.com", genero: "Masculino", pais: "EC", preferencias: { canal: ["WEB"] } },
  { nombre: "Eduardo Carr", email: "eduardo.carr@example.com", genero: "Masculino", pais: "PE", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Eduvigis Lawson", email: "eduvigis.lawson@example.com", genero: "Otro", pais: "HN", preferencias: { canal: ["WEB"] } },
  { nombre: "Efrén Jacobs", email: "efren.jacobs@example.com", genero: "Masculino", pais: "PA", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Elena Obrien", email: "elena.obrien@example.com", genero: "Femenino", pais: "CO", preferencias: { canal: ["WEB"] } },
  { nombre: "Elías Lynch", email: "elias.lynch@example.com", genero: "Masculino", pais: "JM", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Elisa Singh", email: "elisa.singh@example.com", genero: "Femenino", pais: "BZ", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Eliseo Vega", email: "eliseo.vega@example.com", genero: "Masculino", pais: "GT", preferencias: { canal: ["WEB"] } },
  { nombre: "Elvira Bishop", email: "elvira.bishop@example.com", genero: "Femenino", pais: "MX", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Emilia Montgomery", email: "emilia.montgomery@example.com", genero: "Femenino", pais: "TT", preferencias: { canal: ["WEB"] } },
  { nombre: "Emiliano Oliver", email: "emiliano.oliver@example.com", genero: "Masculino", pais: "CL", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Emilio Jensen", email: "emilio.jensen@example.com", genero: "Masculino", pais: "PY", preferencias: { canal: ["WEB"] } },
  { nombre: "Encarnación Harvey", email: "encarnacion.harvey@example.com", genero: "Femenino", pais: "SV", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Enrique Williamson", email: "enrique.williamson@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB"] } },
  { nombre: "Epifanía Gilbert", email: "epifania.gilbert@example.com", genero: "Femenino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Erico Dean", email: "erico.dean@example.com", genero: "Masculino", pais: "US", preferencias: { canal: ["WEB"] } },
  { nombre: "Ernesto Sims", email: "ernesto.sims@example.com", genero: "Masculino", pais: "BB", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Esdras Espinoza", email: "esdras.espinoza@example.com", genero: "Masculino", pais: "DO", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Esiquio Howell", email: "esiquio.howell@example.com", genero: "Masculino", pais: "GD", preferencias: { canal: ["WEB"] } },
  { nombre: "Esperanza Li", email: "esperanza.li@example.com", genero: "Femenino", pais: "HN", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Esteban Wong", email: "esteban.wong@example.com", genero: "Masculino", pais: "UY", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Ester Reid", email: "ester.reid@example.com", genero: "Femenino", pais: "BZ", preferencias: { canal: ["WEB"] } },
  { nombre: "Esther Hanson", email: "esther.hanson@example.com", genero: "Femenino", pais: "EC", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Eugenia Le", email: "eugenia.le@example.com", genero: "Femenino", pais: "JM", preferencias: { canal: ["WEB"] } },
  { nombre: "Eugenio Mccoy", email: "eugenio.mccoy@example.com", genero: "Masculino", pais: "CA", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Eulalia Garrett", email: "eulalia.garrett@example.com", genero: "Femenino", pais: "BO", preferencias: { canal: ["WEB"] } },
  { nombre: "Eusebio Burton", email: "eusebio.burton@example.com", genero: "Masculino", pais: "SV", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Eva Fuller", email: "eva.fuller@example.com", genero: "Femenino", pais: "CL", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Evaristo Wang", email: "evaristo.wang@example.com", genero: "Masculino", pais: "VE", preferencias: { canal: ["WEB"] } },
  { nombre: "Ezequiel Weber", email: "ezequiel.weber@example.com", genero: "Masculino", pais: "GT", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Fabián Welch", email: "fabian.welch@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB"] } },
  { nombre: "Fabio Rojas", email: "fabio.rojas@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Fabiola Lucas", email: "fabiola.lucas@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["WEB"] } },
  { nombre: "Facundo Marquez", email: "facundo.marquez@example.com", genero: "Masculino", pais: "PY", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Fátima Fields", email: "fatima.fields@example.com", genero: "Femenino", pais: "TT", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Faustino Park", email: "faustino.park@example.com", genero: "Masculino", pais: "JM", preferencias: { canal: ["WEB"] } },
  { nombre: "Fausto Yang", email: "fausto.yang@example.com", genero: "Masculino", pais: "DO", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Federico Little", email: "federico.little@example.com", genero: "Masculino", pais: "EC", preferencias: { canal: ["WEB"] } },
  { nombre: "Feliciano Banks", email: "feliciano.banks@example.com", genero: "Masculino", pais: "US", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Felipe Padilla", email: "felipe.padilla@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Félix Day", email: "felix.day@example.com", genero: "Masculino", pais: "CA", preferencias: { canal: ["WEB"] } },
  { nombre: "Fermín Walsh", email: "fermin.walsh@example.com", genero: "Masculino", pais: "PA", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Fernando Bowman", email: "fernando.bowman@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Fidel Schultz", email: "fidel.schultz@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB"] } },
  { nombre: "Fortunato Luna", email: "fortunato.luna@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Francesc Fowler", email: "francesc.fowler@example.com", genero: "Masculino", pais: "UY", preferencias: { canal: ["WEB"] } },
  { nombre: "Francisca Mejia", email: "francisca.mejia@example.com", genero: "Femenino", pais: "PE", preferencias: { canal: ["TIENDA"] } }
]);

db.clientes.insertMany([
  { nombre: "Francisco Davidson", email: "francisco.davidson@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Fulgencio Acosta", email: "fulgencio.acosta@example.com", genero: "Masculino", pais: "PE", preferencias: { canal: ["WEB"] } },
  { nombre: "Gabriel Brewer", email: "gabriel.brewer@example.com", genero: "Masculino", pais: "US", preferencias: { canal: ["WEB"] } },
  { nombre: "Gema May", email: "gema.may@example.com", genero: "Femenino", pais: "CL", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Genoveva Holland", email: "genoveva.holland@example.com", genero: "Femenino", pais: "CO", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Gerardo Juarez", email: "gerardo.juarez@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB"] } },
  { nombre: "Germán Newman", email: "german.newman@example.com", genero: "Masculino", pais: "EC", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Gertrudis Pearson", email: "gertrudis.pearson@example.com", genero: "Femenino", pais: "UY", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Gisela Curtis", email: "gisela.curtis@example.com", genero: "Femenino", pais: "BZ", preferencias: { canal: ["WEB"] } },
  { nombre: "Gloria Cortez", email: "gloria.cortez@example.com", genero: "Femenino", pais: "JM", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Godofredo Douglas", email: "godofredo.douglas@example.com", genero: "Masculino", pais: "VE", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Gonzalo Schneider", email: "gonzalo.schneider@example.com", genero: "Masculino", pais: "TT", preferencias: { canal: ["WEB"] } },
  { nombre: "Gregorio Joseph", email: "gregorio.joseph@example.com", genero: "Masculino", pais: "PA", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Guadalupe Barrett", email: "guadalupe.barrett@example.com", genero: "Otro", pais: "HN", preferencias: { canal: ["WEB"] } },
  { nombre: "Guido Navarro", email: "guido.navarro@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Guillermo Figueroa", email: "guillermo.figueroa@example.com", genero: "Masculino", pais: "CU", preferencias: { canal: ["WEB"] } },
  { nombre: "Gustavo Keller", email: "gustavo.keller@example.com", genero: "Masculino", pais: "AG", preferencias: { canal: ["WEB"] } },
  { nombre: "Guzmán Avila", email: "guzman.avila@example.com", genero: "Masculino", pais: "GD", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Héctor Wade", email: "hector.wade@example.com", genero: "Masculino", pais: "GT", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Heliodoro Molina", email: "heliodoro.molina@example.com", genero: "Masculino", pais: "SR", preferencias: { canal: ["WEB"] } },
  { nombre: "Heraclio Stanley", email: "heraclio.stanley@example.com", genero: "Masculino", pais: "BO", preferencias: { canal: ["WEB"] } },
  { nombre: "Heriberto Hopkins", email: "heriberto.hopkins@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Hilarión Campos", email: "hilarion.campos@example.com", genero: "Masculino", pais: "EC", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Hildegarda Barnett", email: "hildegarda.barnett@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["WEB"] } },
  { nombre: "Homero Bates", email: "homero.bates@example.com", genero: "Masculino", pais: "SV", preferencias: { canal: ["WEB"] } },
  { nombre: "Honorato Chambers", email: "honorato.chambers@example.com", genero: "Masculino", pais: "BR", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Honorio Caldwell", email: "honorio.caldwell@example.com", genero: "Masculino", pais: "UY", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Hugo Beck", email: "hugo.beck@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB"] } },
  { nombre: "Humberto Lambert", email: "humberto.lambert@example.com", genero: "Masculino", pais: "PY", preferencias: { canal: ["WEB"] } },
  { nombre: "Ifigenia Miranda", email: "ifigenia.miranda@example.com", genero: "Femenino", pais: "CO", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Ignacio Byrd", email: "ignacio.byrd@example.com", genero: "Masculino", pais: "DO", preferencias: { canal: ["WEB"] } },
  { nombre: "Ildefonso Craig", email: "ildefonso.craig@example.com", genero: "Masculino", pais: "EC", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Inés Ayala", email: "ines.ayala@example.com", genero: "Femenino", pais: "CL", preferencias: { canal: ["WEB"] } },
  { nombre: "Inmaculada Lowe", email: "inmaculada.lowe@example.com", genero: "Femenino", pais: "JM", preferencias: { canal: ["WEB"] } },
  { nombre: "Inocencio Frazier", email: "inocencio.frazier@example.com", genero: "Masculino", pais: "HN", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Irene Powers", email: "irene.powers@example.com", genero: "Femenino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Ireneo Neal", email: "ireneo.neal@example.com", genero: "Masculino", pais: "PE", preferencias: { canal: ["WEB"] } },
  { nombre: "Isaac Leonard", email: "isaac.leonard@example.com", genero: "Masculino", pais: "SV", preferencias: { canal: ["WEB"] } },
  { nombre: "Isabel Gregory", email: "isabel.gregory@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Isaías Carrillo", email: "isaias.carrillo@example.com", genero: "Masculino", pais: "CU", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Isidro Sutton", email: "isidro.sutton@example.com", genero: "Masculino", pais: "HT", preferencias: { canal: ["WEB"] } },
  { nombre: "Ismael Fleming", email: "ismael.fleming@example.com", genero: "Masculino", pais: "US", preferencias: { canal: ["WEB"] } },
  { nombre: "Iván Rhodes", email: "ivan.rhodes@example.com", genero: "Masculino", pais: "AG", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Jacinto Shelton", email: "jacinto.shelton@example.com", genero: "Masculino", pais: "JM", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Jacob Schwartz", email: "jacob.schwartz@example.com", genero: "Masculino", pais: "PA", preferencias: { canal: ["WEB"] } },
  { nombre: "Jacobo Norris", email: "jacobo.norris@example.com", genero: "Masculino", pais: "CA", preferencias: { canal: ["WEB"] } },
  { nombre: "Jaime Jennings", email: "jaime.jennings@example.com", genero: "Masculino", pais: "HN", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Jaume Watts", email: "jaume.watts@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB"] } },
  { nombre: "Javier Duran", email: "javier.duran@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Jeremías Walters", email: "jeremias.walters@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB"] } },
  { nombre: "Jerónimo Cohen", email: "jeronimo.cohen@example.com", genero: "Masculino", pais: "SV", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Jesús Mcdaniel", email: "jesus.mcdaniel@example.com", genero: "Masculino", pais: "BB", preferencias: { canal: ["WEB"] } },
  { nombre: "Joan Moran", email: "joan.moran@example.com", genero: "Otro", pais: "BZ", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Joaquím Parks", email: "joaquim.parks@example.com", genero: "Masculino", pais: "BR", preferencias: { canal: ["WEB"] } },
  { nombre: "Joaquín Steele", email: "joaquin.steele@example.com", genero: "Masculino", pais: "JM", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Joel Vaughn", email: "joel.vaughn@example.com", genero: "Masculino", pais: "EC", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Jonás Becker", email: "jonas.becker@example.com", genero: "Masculino", pais: "TT", preferencias: { canal: ["WEB"] } },
  { nombre: "Jonathan Holt", email: "jonathan.holt@example.com", genero: "Masculino", pais: "GT", preferencias: { canal: ["WEB"] } },
  { nombre: "Jordi Deleon", email: "jordi.deleon@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Jorge Barker", email: "jorge.barker@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB"] } },
  { nombre: "Josafat Terry", email: "josafat.terry@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB"] } },
  { nombre: "José Hale", email: "jose.hale@example.com", genero: "Masculino", pais: "UY", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Josefa Leon", email: "josefa.leon@example.com", genero: "Femenino", pais: "PE", preferencias: { canal: ["WEB"] } },
  { nombre: "Josefina Hail", email: "josefina.hail@example.com", genero: "Femenino", pais: "HN", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Josep Benson", email: "josep.benson@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB"] } },
  { nombre: "Josué Haynes", email: "josue.haynes@example.com", genero: "Masculino", pais: "AG", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Juan Horton", email: "juan.horton@example.com", genero: "Masculino", pais: "BR", preferencias: { canal: ["WEB"] } },
  { nombre: "Juana Miles", email: "juana.miles@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Julia Lyons", email: "julia.lyons@example.com", genero: "Femenino", pais: "SV", preferencias: { canal: ["WEB"] } },
  { nombre: "Julián Pham", email: "julian.pham@example.com", genero: "Masculino", pais: "EC", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Julio Graves", email: "julio.graves@example.com", genero: "Masculino", pais: "DO", preferencias: { canal: ["WEB"] } },
  { nombre: "Justino Bush", email: "justino.bush@example.com", genero: "Masculino", pais: "BO", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Juvenal Thornton", email: "juvenal.thornton@example.com", genero: "Masculino", pais: "VE", preferencias: { canal: ["WEB"] } },
  { nombre: "Ladislao Wolfe", email: "ladislao.wolfe@example.com", genero: "Masculino", pais: "CL", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Laura Warner", email: "laura.warner@example.com", genero: "Femenino", pais: "JM", preferencias: { canal: ["WEB"] } },
  { nombre: "Laureano Cabrera", email: "laureano.cabrera@example.com", genero: "Masculino", pais: "HN", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Lázaro Mckinney", email: "lazaro.mckinney@example.com", genero: "Masculino", pais: "GT", preferencias: { canal: ["WEB"] } },
  { nombre: "Leandro Mann", email: "leandro.mann@example.com", genero: "Masculino", pais: "BB", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Leocadia Zimmerman", email: "leocadia.zimmerman@example.com", genero: "Femenino", pais: "BZ", preferencias: { canal: ["WEB"] } },
  { nombre: "León Dawson", email: "leon.dawson@example.com", genero: "Masculino", pais: "SR", preferencias: { canal: ["WEB"] } },
  { nombre: "Leonardo Lara", email: "leonardo.lara@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Leoncio Fletcher", email: "leoncio.fletcher@example.com", genero: "Masculino", pais: "GD", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Leonor Page", email: "leonor.page@example.com", genero: "Femenino", pais: "PA", preferencias: { canal: ["WEB"] } },
  { nombre: "Leopoldo Mccarthy", email: "leopoldo.mccarthy@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB"] } },
  { nombre: "Lidia Love", email: "lidia.love@example.com", genero: "Femenino", pais: "CO", preferencias: { canal: ["WEB"] } },
  { nombre: "Liduvina Robles", email: "liduvina.robles@example.com", genero: "Femenino", pais: "EC", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Lino Cervantes", email: "lino.cervantes@example.com", genero: "Masculino", pais: "PE", preferencias: { canal: ["WEB"] } },
  { nombre: "Lorena Solis", email: "lorena.solis@example.com", genero: "Femenino", pais: "JM", preferencias: { canal: ["WEB"] } },
  { nombre: "Lorenzo Erickson", email: "lorenzo.erickson@example.com", genero: "Masculino", pais: "CL", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Lourdes Reeves", email: "lourdes.reeves@example.com", genero: "Femenino", pais: "CU", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Lucano Chang", email: "lucano.chang@example.com", genero: "Masculino", pais: "HN", preferencias: { canal: ["WEB"] } },
  { nombre: "Lucas Klein", email: "lucas.klein@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Lucía Salinas", email: "lucia.salinas@example.com", genero: "Femenino", pais: "AR", preferencias: { canal: ["WEB"] } },
  { nombre: "Luciano Fuentes", email: "luciano.fuentes@example.com", genero: "Masculino", pais: "BR", preferencias: { canal: ["WEB"] } },
  { nombre: "Lucrecia Baldwin", email: "lucrecia.baldwin@example.com", genero: "Femenino", pais: "GT", preferencias: { canal: ["TIENDA"] } },
  { nombre: "Luis Daniel", email: "luis.daniel@example.com", genero: "Masculino", pais: "DO", preferencias: { canal: ["WEB"] } },
  { nombre: "Luisa Simon", email: "luisa.simon@example.com", genero: "Femenino", pais: "VE", preferencias: { canal: ["WEB","TIENDA"] } },
  { nombre: "Luz Velasquez", email: "luz.velasquez@example.com", genero: "Femenino", pais: "PA", preferencias: { canal: ["WEB"] } },
  { nombre: "Macario Hardy", email: "macario.hardy@example.com", genero: "Masculino", pais: "GY", preferencias: { canal: ["WEB"] } },
  { nombre: "Magdalena Higgins", email: "magdalena.higgins@example.com", genero: "Femenino", pais: "SV", preferencias: { canal: ["WEB","TIENDA"] } }
]);

db.clientes.insertMany([
    { nombre: "Manuel Aguirre", email: "manuel.aguirre@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Manuela Lin", email: "manuela.lin@example.com", genero: "Femenino", pais: "HN", preferencias: { canal: ["WEB"] } },
    { nombre: "Mar Cummings", email: "mar.cummings@example.com", genero: "Otro", pais: "EC", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Marc Chandler", email: "marc.chandler@example.com", genero: "Masculino", pais: "BZ", preferencias: { canal: ["WEB"] } },
    { nombre: "Marcelino Sharp", email: "marcelino.sharp@example.com", genero: "Masculino", pais: "UY", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Marcelo Barber", email: "marcelo.barber@example.com", genero: "Masculino", pais: "BB", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Marcial Bowen", email: "marcial.bowen@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB"] } },
    { nombre: "Marciano Ochoa", email: "marciano.ochoa@example.com", genero: "Masculino", pais: "JM", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Marcos Dennis", email: "marcos.dennis@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB"] } },
    { nombre: "Margarita Robbins", email: "margarita.robbins@example.com", genero: "Femenino", pais: "GD", preferencias: { canal: ["TIENDA"] } },
    { nombre: "María Liu", email: "maria.liu@example.com", genero: "Femenino", pais: "SV", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Mariano Ramsey", email: "mariano.ramsey@example.com", genero: "Masculino", pais: "DO", preferencias: { canal: ["WEB"] } },
    { nombre: "Marina Francis", email: "marina.francis@example.com", genero: "Femenino", pais: "PE", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Mario Griffith", email: "mario.griffith@example.com", genero: "Masculino", pais: "PA", preferencias: { canal: ["WEB"] } },
    { nombre: "Marta Paul", email: "marta.paul@example.com", genero: "Femenino", pais: "VC", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Martín Blair", email: "martin.blair@example.com", genero: "Masculino", pais: "EC", preferencias: { canal: ["WEB"] } },
    { nombre: "Mateo Oconnor", email: "mateo.oconnor@example.com", genero: "Masculino", pais: "HT", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Matías Cardenas", email: "matias.cardenas@example.com", genero: "Masculino", pais: "AG", preferencias: { canal: ["WEB"] } },
    { nombre: "Matilde Pacheco", email: "matilde.pacheco@example.com", genero: "Femenino", pais: "GT", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Mauricio Cross", email: "mauricio.cross@example.com", genero: "Masculino", pais: "SR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Maximiliano Calderon", email: "maximiliano.calderon@example.com", genero: "Masculino", pais: "US", preferencias: { canal: ["WEB"] } },
    { nombre: "Melchor Quinn", email: "melchor.quinn@example.com", genero: "Masculino", pais: "CL", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Mercedes Moss", email: "mercedes.moss@example.com", genero: "Femenino", pais: "BZ", preferencias: { canal: ["WEB"] } },
    { nombre: "Miguel Swanson", email: "miguel.swanson@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Milagros Chan", email: "milagros.chan@example.com", genero: "Femenino", pais: "AR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Miqueas Rivas", email: "miqueas.rivas@example.com", genero: "Masculino", pais: "PA", preferencias: { canal: ["WEB"] } },
    { nombre: "Míriam Khan", email: "miriam.khan@example.com", genero: "Femenino", pais: "PY", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Mohamed Rodgers", email: "mohamed.rodgers@example.com", genero: "Masculino", pais: "CL", preferencias: { canal: ["WEB"] } },
    { nombre: "Moisés Serrano", email: "moises.serrano@example.com", genero: "Masculino", pais: "TT", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Mónica Fitzgerald", email: "monica.fitzgerald@example.com", genero: "Femenino", pais: "EC", preferencias: { canal: ["WEB"] } },
    { nombre: "Montserrat Rosales", email: "montserrat.rosales@example.com", genero: "Femenino", pais: "JM", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Narciso Stevenson", email: "narciso.stevenson@example.com", genero: "Masculino", pais: "HN", preferencias: { canal: ["WEB"] } },
    { nombre: "Natalia Christensen", email: "natalia.christensen@example.com", genero: "Femenino", pais: "MX", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Natividad Manning", email: "natividad.manning@example.com", genero: "Femenino", pais: "DM", preferencias: { canal: ["WEB"] } },
    { nombre: "Nazario Gill", email: "nazario.gill@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Nemesio Curry", email: "nemesio.curry@example.com", genero: "Masculino", pais: "DO", preferencias: { canal: ["WEB"] } },
    { nombre: "Nicanor Mclaughlin", email: "nicanor.mclaughlin@example.com", genero: "Masculino", pais: "GD", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Nicodemo Harmon", email: "nicodemo.harmon@example.com", genero: "Masculino", pais: "UY", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Nicolás Mcgee", email: "nicolas.mcgee@example.com", genero: "Masculino", pais: "BB", preferencias: { canal: ["WEB"] } },
    { nombre: "Nicomedes Gross", email: "nicomedes.gross@example.com", genero: "Otro", pais: "JM", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Nieves Doyle", email: "nieves.doyle@example.com", genero: "Femenino", pais: "PE", preferencias: { canal: ["WEB"] } },
    { nombre: "Noé Garner", email: "noe.garner@example.com", genero: "Masculino", pais: "VE", preferencias: { canal: ["WEB"] } },
    { nombre: "Noelia Newton", email: "noelia.newton@example.com", genero: "Femenino", pais: "EC", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Norberto Burgess", email: "norberto.burgess@example.com", genero: "Masculino", pais: "SV", preferencias: { canal: ["WEB"] } },
    { nombre: "Nuria Reese", email: "nuria.reese@example.com", genero: "Femenino", pais: "US", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Octavio Walton", email: "octavio.walton@example.com", genero: "Masculino", pais: "CL", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Odón Blake", email: "odon.blake@example.com", genero: "Masculino", pais: "AG", preferencias: { canal: ["WEB"] } },
    { nombre: "Olga Trujillo", email: "olga.trujillo@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Onésimo Adkins", email: "onesimo.adkins@example.com", genero: "Masculino", pais: "PY", preferencias: { canal: ["WEB"] } },
    { nombre: "Orestes Brady", email: "orestes.brady@example.com", genero: "Masculino", pais: "BR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Oriol Goodman", email: "oriol.goodman@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB"] } },
    { nombre: "Oscar Roman", email: "oscar.roman@example.com", genero: "Masculino", pais: "CA", preferencias: { canal: ["WEB"] } },
    { nombre: "Óscar Webster", email: "oscar.webster@example.com", genero: "Masculino", pais: "JM", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Oseas Goodwin", email: "oseas.goodwin@example.com", genero: "Masculino", pais: "GD", preferencias: { canal: ["WEB"] } },
    { nombre: "Oswaldo Fischer", email: "oswaldo.fischer@example.com", genero: "Masculino", pais: "GT", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Otilia Huang", email: "otilia.huang@example.com", genero: "Femenino", pais: "LC", preferencias: { canal: ["WEB"] } },
    { nombre: "Oto Potter", email: "oto.potter@example.com", genero: "Masculino", pais: "EC", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Pablo Delacruz", email: "pablo.delacruz@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB"] } },
    { nombre: "Pancracio Montoya", email: "pancracio.montoya@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Pascual Todd", email: "pascual.todd@example.com", genero: "Masculino", pais: "VE", preferencias: { canal: ["WEB"] } },
    { nombre: "Patricia Wu", email: "patricia.wu@example.com", genero: "Femenino", pais: "PA", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Patricio Hines", email: "patricio.hines@example.com", genero: "Masculino", pais: "HN", preferencias: { canal: ["WEB"] } },
    { nombre: "Paula Mullins", email: "paula.mullins@example.com", genero: "Femenino", pais: "JM", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Pedro Castaneda", email: "pedro.castaneda@example.com", genero: "Masculino", pais: "SV", preferencias: { canal: ["WEB"] } },
    { nombre: "Petronila Malone", email: "petronila.malone@example.com", genero: "Femenino", pais: "CL", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Pilar Cannon", email: "pilar.cannon@example.com", genero: "Femenino", pais: "EC", preferencias: { canal: ["WEB"] } },
    { nombre: "Pío Tate", email: "pio.tate@example.com", genero: "Masculino", pais: "BR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Poncio Mack", email: "poncio.mack@example.com", genero: "Masculino", pais: "CA", preferencias: { canal: ["WEB"] } },
    { nombre: "Porfirio Sherman", email: "porfirio.sherman@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Primo Hubbard", email: "primo.hubbard@example.com", genero: "Masculino", pais: "GT", preferencias: { canal: ["WEB"] } },
    { nombre: "Priscila Hodges", email: "priscila.hodges@example.com", genero: "Femenino", pais: "LC", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Probo Zhang", email: "probo.zhang@example.com", genero: "Masculino", pais: "PA", preferencias: { canal: ["WEB"] } },
    { nombre: "Purificación Guerra", email: "purificacion.guerra@example.com", genero: "Femenino", pais: "HN", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Rafael Wolf", email: "rafael.wolf@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Raimundo Valencia", email: "raimundo.valencia@example.com", genero: "Masculino", pais: "BS", preferencias: { canal: ["WEB"] } },
    { nombre: "Ramiro Franco", email: "ramiro.franco@example.com", genero: "Masculino", pais: "BZ", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Ramón Saunders", email: "ramon.saunders@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB"] } },
    { nombre: "Raquel Rowe", email: "raquel.rowe@example.com", genero: "Femenino", pais: "SV", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Raúl Gallagher", email: "raul.gallagher@example.com", genero: "Masculino", pais: "JM", preferencias: { canal: ["WEB"] } },
    { nombre: "Rebeca Farmer", email: "rebeca.farmer@example.com", genero: "Femenino", pais: "GD", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Reinaldo Hammond", email: "reinaldo.hammond@example.com", genero: "Masculino", pais: "AG", preferencias: { canal: ["WEB"] } },
    { nombre: "Remedios Hampton", email: "remedios.hampton@example.com", genero: "Femenino", pais: "HN", preferencias: { canal: ["WEB"] } },
    { nombre: "Renato Townsend", email: "renato.townsend@example.com", genero: "Masculino", pais: "PE", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Ricardo Ingram", email: "ricardo.ingram@example.com", genero: "Masculino", pais: "US", preferencias: { canal: ["WEB"] } },
    { nombre: "Rigoberto Wise", email: "rigoberto.wise@example.com", genero: "Masculino", pais: "UY", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Rita Gallegos", email: "rita.gallegos@example.com", genero: "Femenino", pais: "CO", preferencias: { canal: ["WEB"] } },
    { nombre: "Roberto Clarke", email: "roberto.clarke@example.com", genero: "Masculino", pais: "HT", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Rocío Barton", email: "rocio.barton@example.com", genero: "Femenino", pais: "BB", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Rodrigo Schroeder", email: "rodrigo.schroeder@example.com", genero: "Masculino", pais: "JM", preferencias: { canal: ["WEB"] } },
    { nombre: "Rogelio Maxwell", email: "rogelio.maxwell@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Román Waters", email: "roman.waters@example.com", genero: "Masculino", pais: "GT", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Romualdo Logan", email: "romualdo.logan@example.com", genero: "Masculino", pais: "NI", preferencias: { canal: ["WEB"] } },
    { nombre: "Roque Camacho", email: "roque.camacho@example.com", genero: "Masculino", pais: "SR", preferencias: { canal: ["WEB"] } },
    { nombre: "Rosa Strickland", email: "rosa.strickland@example.com", genero: "Femenino", pais: "TT", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Rosalia Norman", email: "rosalia.norman@example.com", genero: "Femenino", pais: "AR", preferencias: { canal: ["WEB"] } },
    { nombre: "Rosario Person", email: "rosario.person@example.com", genero: "Femenino", pais: "PE", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Rosendo Colon", email: "rosendo.colon@example.com", genero: "Masculino", pais: "BZ", preferencias: { canal: ["WEB"] } },
    { nombre: "Rubén Parsons", email: "ruben.parsons@example.com", genero: "Masculino", pais: "DO", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Rufo Frank", email: "rufo.frank@example.com", genero: "Masculino", pais: "CL", preferencias: { canal: ["WEB"] } },
    { nombre: "Ruperto Harrington", email: "ruperto.harrington@example.com", genero: "Masculino", pais: "GD", preferencias: { canal: ["WEB","TIENDA"] } }
])

db.miColeccion.insertMany([
    { nombre: "Salomé Glover", email: "salome.glover@example.com", genero: "Femenino", pais: "MX", preferencias: { canal: ["WEB"] } },
    { nombre: "Salomón Osborne", email: "salomon.osborne@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["TIENDA","WEB"] } },
    { nombre: "Salvador Buchanan", email: "salvador.buchanan@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Salvio Casey", email: "salvio.casey@example.com", genero: "Masculino", pais: "ES", preferencias: { canal: ["WEB"] } },
    { nombre: "Samuel Floyd", email: "samuel.floyd@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Sandra Patton", email: "sandra.patton@example.com", genero: "Femenino", pais: "MX", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Sansón Ibarra", email: "sanson.ibarra@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB"] } },
    { nombre: "Santiago Ball", email: "santiago.ball@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Sara Tyler", email: "sara.tyler@example.com", genero: "Femenino", pais: "ES", preferencias: { canal: ["WEB"] } },
    { nombre: "Sebastián Suarez", email: "sebastian.suarez@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Segismundo Bowers", email: "segismundo.bowers@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB"] } },
    { nombre: "Sergio Orozco", email: "sergio.orozco@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Severino Salas", email: "severino.salas@example.com", genero: "Masculino", pais: "ES", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Silvia Cobb", email: "silvia.cobb@example.com", genero: "Femenino", pais: "MX", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Simeón Gibbs", email: "simeon.gibbs@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB"] } },
    { nombre: "Simón Andrade", email: "simon.andrade@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Siro Bauer", email: "siro.bauer@example.com", genero: "Masculino", pais: "ES", preferencias: { canal: ["WEB"] } },
    { nombre: "Sixto Conner", email: "sixto.conner@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Sofía Moody", email: "sofia.moody@example.com", genero: "Femenino", pais: "MX", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Soledad Escobar", email: "soledad.escobar@example.com", genero: "Femenino", pais: "AR", preferencias: { canal: ["WEB"] } },
    { nombre: "Sonia Mcguire", email: "sonia.mcguire@example.com", genero: "Femenino", pais: "CO", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Susana Lloyd", email: "susana.lloyd@example.com", genero: "Femenino", pais: "ES", preferencias: { canal: ["WEB"] } },
    { nombre: "Tadeo Mueller", email: "tadeo.mueller@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Tarsicio Hartman", email: "tarsicio.hartman@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB"] } },
    { nombre: "Teodora French", email: "teodora.french@example.com", genero: "Femenino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Teodosia Kramer", email: "teodosia.kramer@example.com", genero: "Femenino", pais: "ES", preferencias: { canal: ["WEB"] } },
    { nombre: "Teófanes Mcbride", email: "teofanes.mcbride@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Teófila Pope", email: "teofila.pope@example.com", genero: "Femenino", pais: "MX", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Teresa Lindsey", email: "teresa.lindsey@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["WEB"] } },
    { nombre: "Timoteo Velazquez", email: "timoteo.velazquez@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Tito Norton", email: "tito.norton@example.com", genero: "Masculino", pais: "ES", preferencias: { canal: ["WEB"] } },
    { nombre: "Tobías Mccormick", email: "tobias.mccormick@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Tomas Sparks", email: "tomas.sparks@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB"] } },
    { nombre: "Tomás Flynn", email: "tomas.flynn@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Toribio Yates", email: "toribio.yates@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Trinidad Hogan", email: "trinidad.hogan@example.com", genero: "Femenino", pais: "CO", preferencias: { canal: ["WEB"] } },
    { nombre: "Ubaldo Marsh", email: "ubaldo.marsh@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Urbano Macias", email: "urbano.macias@example.com", genero: "Masculino", pais: "ES", preferencias: { canal: ["WEB"] } },
    { nombre: "Úrsula Villanueva", email: "ursula.villanueva@example.com", genero: "Femenino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Valentín Zamora", email: "valentin.zamora@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Valeriano Pratt", email: "valeriano.pratt@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB"] } },
    { nombre: "Vanesa Stokes", email: "vanesa.stokes@example.com", genero: "Femenino", pais: "MX", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Velerio Owen", email: "velerio.owen@example.com", genero: "Masculino", pais: "ES", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Venancio Ballard", email: "venancio.ballard@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB"] } },
    { nombre: "Verónica Lang", email: "veronica.lang@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Vicenta Brock", email: "vicenta.brock@example.com", genero: "Femenino", pais: "CO", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Vicente Villarreal", email: "vicente.villarreal@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB"] } },
    { nombre: "Víctor Charles", email: "victor.charles@example.com", genero: "Masculino", pais: "ES", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Victoria Drake", email: "victoria.drake@example.com", genero: "Femenino", pais: "AR", preferencias: { canal: ["WEB"] } },
    { nombre: "Victorino Barrera", email: "victorino.barrera@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Victorio Cain", email: "victorio.cain@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Vidal Patrick", email: "vidal.patrick@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB"] } },
    { nombre: "Virgilio Pineda", email: "virgilio.pineda@example.com", genero: "Masculino", pais: "ES", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Virginia Burnett", email: "virginia.burnett@example.com", genero: "Femenino", pais: "CO", preferencias: { canal: ["WEB"] } },
    { nombre: "Vladimiro Mercado", email: "vladimiro.mercado@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Wilfredo Santana", email: "wilfredo.santana@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB"] } },
    { nombre: "Xavier Shepherd", email: "xavier.shepherd@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Yolanda Bautista", email: "yolanda.bautista@example.com", genero: "Femenino", pais: "ES", preferencias: { canal: ["WEB"] } },
    { nombre: "Zacarías Ali", email: "zacarias.ali@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Zaqueo Shaffer", email: "zaqueo.shaffer@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Aarón Lamb", email: "aaron.lamb@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB"] } },
    { nombre: "Abdón Trevino", email: "abdon.trevino@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Abel Mckenzie", email: "abel.mckenzie@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB"] } },
    { nombre: "Abelardo Hess", email: "abelardo.hess@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Abrahán Beil", email: "abrahan.beil@example.com", genero: "Masculino", pais: "ES", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Absalón Olsen", email: "absalon.olsen@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB"] } },
    { nombre: "Acacio Cochran", email: "acacio.cochran@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Adalberto Morton", email: "adalberto.morton@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB"] } },
    { nombre: "Adán Nash", email: "adan.nash@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Adela Wilkins", email: "adela.wilkins@example.com", genero: "Femenino", pais: "ES", preferencias: { canal: ["WEB"] } },
    { nombre: "Adelaida Petersen", email: "adelaida.petersen@example.com", genero: "Femenino", pais: "AR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Adolfo Briggs", email: "adolfo.briggs@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB"] } },
    { nombre: "Adón Shah", email: "adon.shah@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Adrián Roth", email: "adrian.roth@example.com", genero: "Masculino", pais: "ES", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Agustín Nicholson", email: "agustin.nicholson@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB"] } },
    { nombre: "Aitor Holloway", email: "aitor.holloway@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Alba Lozano", email: "alba.lozano@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Albert Flowers", email: "albert.flowers@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB"] } },
    { nombre: "Alberto Rangel", email: "alberto.rangel@example.com", genero: "Masculino", pais: "ES", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Albina Hoover", email: "albina.hoover@example.com", genero: "Femenino", pais: "CO", preferencias: { canal: ["WEB"] } },
    { nombre: "Alejandra Arias", email: "alejandra.arias@example.com", genero: "Femenino", pais: "AR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Alejandro Short", email: "alejandro.short@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB"] } },
    { nombre: "Alejo Mora", email: "alejo.mora@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Alfonso Valenzuela", email: "alfonso.valenzuela@example.com", genero: "Masculino", pais: "ES", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Alfredo Bryan", email: "alfredo.bryan@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB"] } },
    { nombre: "Alicia Meyers", email: "alicia.meyers@example.com", genero: "Femenino", pais: "MX", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Alipio Weiss", email: "alipio.weiss@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["WEB"] } },
    { nombre: "Almudena Underwood", email: "almudena.underwood@example.com", genero: "Femenino", pais: "ES", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Alonso Bass", email: "alonso.bass@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Álvaro Greer", email: "alvaro.greer@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["WEB"] } },
    { nombre: "Amadeo Summers", email: "amadeo.summers@example.com", genero: "Masculino", pais: "MX", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Amaro Houston", email: "amaro.houston@example.com", genero: "Masculino", pais: "ES", preferencias: { canal: ["WEB"] } },
    { nombre: "Ambrosio Carson", email: "ambrosio.carson@example.com", genero: "Masculino", pais: "AR", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Amelia Morrow", email: "amelia.morrow@example.com", genero: "Femenino", pais: "CR", preferencias: { canal: ["WEB"] } },
    { nombre: "Amparo Clayton", email: "amparo.clayton@example.com", genero: "Femenino", pais: "MX", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Ana Whitaker", email: "ana.whitaker@example.com", genero: "Femenino", pais: "ES", preferencias: { canal: ["WEB"] } },
    { nombre: "Ananías Decker", email: "ananias.decker@example.com", genero: "Masculino", pais: "CO", preferencias: { canal: ["TIENDA"] } },
    { nombre: "Anastasia Yoder", email: "anastasia.yoder@example.com", genero: "Femenino", pais: "AR", preferencias: { canal: ["WEB"] } },
    { nombre: "Anatolio Collier", email: "anatolio.collier@example.com", genero: "Masculino", pais: "CR", preferencias: { canal: ["WEB","TIENDA"] } },
    { nombre: "Andrea Carey", email: "andrea.carey@example.com", genero: "Femenino", pais: "MX", preferencias: { canal: ["WEB"] } }
]);
